### ISSUE TITLE
Please provide tooltips in the dialog

### ISSUE THREAD

**Issue by pcav** [jawensi/DEMto3D#5]
Small icons (world, arrows, etc.) use is not obvious. Please provide a short description as a tooltip.

**Comment by jawensi** [comment]
Icons in the dialogs has tooltip:

	self.FullExtToolButton.setToolTip(_translate("DEMto3DDialogBase", "Select full extent", None))
	self.FullExtToolButton.setStatusTip(_translate("DEMto3DDialogBase", "Select full extent", None))
	self.FullExtToolButton.setWhatsThis(_translate("DEMto3DDialogBase", "Select full extent", None))
	self.FullExtToolButton.setAccessibleName(_translate("DEMto3DDialogBase", "Select full extent", None))
	self.LayerExtToolButton.setToolTip(_translate("DEMto3DDialogBase", "Select layer extent", None))
	self.LayerExtToolButton.setStatusTip(_translate("DEMto3DDialogBase", "Select layer extent", None))
	self.LayerExtToolButton.setWhatsThis(_translate("DEMto3DDialogBase", "Select layer extent", None))
	self.LayerExtToolButton.setAccessibleName(_translate("DEMto3DDialogBase", "Select layer extent", None))
	self.CustomExtToolButton.setToolTip(_translate("DEMto3DDialogBase", "Draw extent", None))
	self.CustomExtToolButton.setStatusTip(_translate("DEMto3DDialogBase", "Draw extent", None))
	self.CustomExtToolButton.setWhatsThis(_translate("DEMto3DDialogBase", "Draw extent", None))
	self.CustomExtToolButton.setAccessibleName(_translate("DEMto3DDialogBase", "Draw extent", None))
	self.groupBox_3.setTitle(_translate("DEMto3DDialogBase", "Model size", None))
