### ISSUE TITLE
Move it under raster menu?

### ISSUE THREAD

**Issue by pcav** [jawensi/DEMto3D#8]
So it will be easier to find (if this is appropriate for the plugin).

**Comment by jawensi** [comment]
yes, I think is a better location. Done.

**Comment by pcav** [comment]
Please publish a new version when ready, for inspection and prompt approval.
Thanks.

**Comment by jawensi** [comment]
I published a new version 2.3.1

**Comment by pcav** [comment]
Now published. Please note that I have set it up as experimental, because of the open bugs (rather serious IMHO).
Thanks.
